use_frameworks!

target 'ViewletCreator_Example' do
  pod 'ViewletCreator', :path => '../../'
  pod 'Alamofire', '~> 4.0'

  target 'ViewletCreator_Tests' do
    inherit! :search_paths
    pod 'ViewletCreator', :path => '../../'
  end
end
